name: Dev Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Unzip build zip on VPS instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ${{ secrets.INSTANCE_USERNAME }}
        key: ${{ secrets.INSTANCE_KEY }}
        script: |
          cd /var/www/html/tubes-sig-2
          git pull origin master
          git checkout master
